base:
    use_aug : False
    num_classes : 264
    batch_size : 64
    ep1ochs : 12
    PRECISION : 16    
    PATIENCE : 8    
    seed : 2023
    model : "tf_efficientnet_b0_ns"
    pretrained : True            
    weight_decay : 1e-3
    use_mixup : True
    mixup_alpha : 0.2
    DEVICE : torch.device('cuda' if torch.cuda.is_available() else 'cpu')

data_source:
  root_dir: Data\train_audio
  meta_data: Data\train_metadata.csv

artifacts:
  artifacts_dir: artifacts

  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/data.csv

  split_data:
    processed_data_dir: artifacts/processed_data
    train_images: artifacts/processed_data
    val_images: artifacts/processed_data/val.csv
    train_csv: artifacts/processed_data/train.csv
    val_csv: artifacts/processed_data/val.csv

  reports:
    reports_dir: artifacts/report
    params: artifacts/report/params.json
    scores: artifacts/report/scores.json

  model_dir: artifacts/saved_models
  model_path: artifacts/saved_models/model.joblib


estimators:
  ElasticNet:
    params:
      SR : 32000
      DURATION : 5
      MAX_READ_SAMPLES : 5
      LR : 5e-4
